# Generated by Django 2.2.12 on 2020-06-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description. Yessir'),
            preserve_default=False,
        ),
    ]
