# Generated by Django 2.2.12 on 2020-06-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200607_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество на складе'),
        ),
    ]
