# Generated by Django 2.2.12 on 2020-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200617_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'Футболки'), ('SW', 'Спортивная одежда'), ('OW', 'Верхняя одежда')], max_length=2, verbose_name='Категория'),
        ),
    ]
