# Generated by Django 2.2.12 on 2020-06-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200617_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discarded',
            field=models.BooleanField(default=False),
        ),
    ]
