# Generated by Django 2.2.12 on 2020-06-18 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200618_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
