# Generated by Django 3.0.2 on 2020-01-28 08:16

import courses.models
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('started', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), courses.models.max_value_current_year])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('learning_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Class')),
            ],
            options={
                'ordering': ('learning_class', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(choices=[(1, 'Postgraduate'), (2, 'Associate Professor'), (3, 'Head of Departament')], default=1, max_length=2)),
                ('courses', models.ManyToManyField(blank=True, related_name='teachers', to='courses.Class')),
            ],
            options={
                'ordering': ('position', 'last_name'),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('graduated', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), courses.models.max_value_current_year])),
                ('year_in_school', models.CharField(choices=[(1, 'Freshman'), (2, 'Sophomore'), (3, 'Junior'), (4, 'Senior')], default=1, max_length=2)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='courses.Class')),
            ],
            options={
                'ordering': ('-graduated', 'year_in_school', 'last_name'),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LessonGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], max_length=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student')),
            ],
            options={
                'ordering': ('student', 'lesson', 'grade'),
            },
        ),
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student')),
            ],
            options={
                'ordering': ('student', 'course', 'grade'),
            },
        ),
    ]
