# Generated by Django 3.0.2 on 2020-01-29 05:51

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('started', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), courses.models.max_value_current_year])),
            ],
            options={
                'verbose_name_plural': 'classes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
                ('learning_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Class')),
            ],
            options={
                'ordering': ('learning_class', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PG', 'Postgraduate'), ('AP', 'Associate Professor'), ('HD', 'Head of Departament')], default='PG', max_length=2)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('courses', models.ManyToManyField(blank=True, related_name='teachers', to='courses.Class')),
            ],
            options={
                'ordering': ('position', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduated', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), courses.models.max_value_current_year])),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SP', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='courses.Class')),
            ],
            options={
                'ordering': ('-graduated', 'year_in_school', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='LessonGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], max_length=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student')),
            ],
            options={
                'ordering': ('student', 'lesson', 'grade'),
            },
        ),
        migrations.CreateModel(
            name='ClassGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Student')),
            ],
            options={
                'ordering': ('student', 'course', 'grade'),
            },
        ),
    ]
