# Generated by Django 3.0.2 on 2020-01-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200129_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
