# Generated by Django 2.2.9 on 2020-02-09 09:46

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('started', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), courses.models.max_value_current_year])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], max_length=1)),
            ],
            options={
                'ordering': ('student', 'course', 'grade'),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'ordering': ('course', '-start_time'),
            },
        ),
        migrations.CreateModel(
            name='LessonGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], max_length=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
            ],
            options={
                'ordering': ('student', 'lesson', 'grade'),
            },
        ),
    ]
