# Generated by Django 2.2.9 on 2020-02-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200209_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='location',
            field=models.CharField(blank=True, default='', max_length=80),
            preserve_default=False,
        ),
    ]
