# Generated by Django 3.0.2 on 2020-02-13 16:25

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200209_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course',)},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='yay', max_length=80, verbose_name='Название урока'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='started',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1970), courses.models.max_value_current_year], verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='Содержание урока'),
        ),
    ]
