# Generated by Django 3.0.2 on 2020-02-17 08:41

import courses.mixins
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('started', models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(1970, 1, 1)), django.core.validators.MaxValueValidator(django.utils.timezone.now)], verbose_name='Дата начала')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], max_length=1)),
            ],
            options={
                'ordering': ('student', 'course', 'grade'),
            },
            bases=(models.Model, courses.mixins.GradeMixin),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название урока')),
                ('content', models.TextField(verbose_name='Содержание урока')),
            ],
            options={
                'ordering': ('course',),
            },
        ),
        migrations.CreateModel(
            name='LessonGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], max_length=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
            ],
            options={
                'ordering': ('student', 'lesson', 'grade'),
            },
            bases=(models.Model, courses.mixins.GradeMixin),
        ),
    ]
